### ISSUE TITLE
IDs provided by the caller are not persisted when creating new domain entities

### ISSUE THREAD

**Issue by andrew-d-taylor** [ScottKimball/SMWC#19]
This makes it hard in testing, when we need to create and immediately retrieve a domain class with an ID we've constructed (not auto-generated).

**Comment by ScottKimball** [comment]
If the test is marked as transactional, you should be able to persist the entity and then pass entity.getId() to the entityService.find() method to retrieve the entity from the database. 

This won't work for the controller ITs that create new entities however. If you want to look into another ID generation strategy that won't cause regressions, I'm all for it.
