### ISSUE TITLE
ContactController should handle duplicate attended events gracefully

### ISSUE THREAD

**Issue by andrew-d-taylor** [ScottKimball/SMWC#21]
Currently, when the client makes a PUT request with a contact that contains a duplicate/repeated Event element in its attendedEvents payload, the server throws a 500.

Even though the client code should not provide the option to attend an event twice - restriction soon to be implemented - we should review our server code for other areas where we might be vulnerable to these kind of duplicate submissions. If for nothing else than to respond with something better than a 500.

**Comment by andrew-d-taylor** [comment]
Closed with commit: https://github.com/ScottKimball/SMWC/commit/186d90a2ca50adbcefe1e0794917640473bb0bf9

**Comment by ScottKimball** [comment]
Food for thought:

 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
