### ISSUE TITLE
Add demographic information to the Contact data model

### ISSUE THREAD

**Issue by andrew-d-taylor** [ScottKimball/SMWC#3]
Should include:
- race
- ethnicity
- birthdate
- gender
- disability (boolean)

**Comment by ScottKimball** [comment]
add sexual orientation

**Comment by andrew-d-taylor** [comment]
Occupation should be included.
Income bracket

**Comment by andrew-d-taylor** [comment]
Closed with commit: https://github.com/ScottKimball/SMWC/commit/bec19629a283ecbad7ef00e83df6446f22e7583c
