### ISSUE TITLE
compareTo function of Encounters throwing exceptions

### ISSUE THREAD

**Issue by andrew-d-taylor** [ScottKimball/SMWC#48]
The Encounter compareTo function tries to parse LocalDates from the String 'date' property. The LocalDate.parse() call we're using cannot parse the date format our client code is using when supplying the date property.

We should either be more flexible with our compareTo expectations or reconsider how we're setting date fields server-side.

**Comment by andrew-d-taylor** [comment]
Possibly related to #47

**Comment by ScottKimball** [comment]
Does the date pattern from the client code match the format expected by the datetime formatter?

**Comment by andrew-d-taylor** [comment]
Format currently being sent by the client: 2012-12-12T05:00:00.000Z

**Comment by andrew-d-taylor** [comment]
Reflecting after our discussion today:

Made some headway towards modeling a contact's encounters as a SortedSet (in part, to eliminate the odd behavior described in #47 ), but ran into problems. Hibernate requires that you define how a SortedSet be sorted, specified by annotation. @SortNatural would rely on the Encounter's compareTo method. This seemed like a good idea, but we want the desired date format to be evaluated at runtime based on a properties file, and autowiring that dependency into the Encounter pojo does not seem right. Hibernate also has a @SortComparator annotation, where you can define a comparator class to be used when it instantiates the collection. This seemed like a more appropriate place to autowire the format dependency. Unfortunately, hibernate instantiates this class on its own and not as a DI-bean. So the format dependency fails to be set in the comparator. Working around this - somehow forcing hibernate to use the spring bean - even if possible, smells like an antipattern.

I think we should consider refactoring our String dates to be LocalDates across the domain layer. We could then delegate basic formatting concerns to Jackson.

This and issue #47 are high priorities, as they expose a bug in fundamental domain-level logic.

**Comment by andrew-d-taylor** [comment]
Closed with https://github.com/ScottKimball/SMWC/commit/8eeefc4278e73d92bcf031fb378e2d0de84612c3
