### ISSUE TITLE
User should be able to add an encounter to a contact

### ISSUE THREAD

**Issue by ScottKimball** [ScottKimball/SMWC#6]
The sequence should be roughly as follows:
1. User selects a contact from the contact list
2. User clicks the "add encounter" button
3. User is redirected to the new encounter form
4. User fills out form and clicks the "enter" button
5. User is redirected to that contact's details page.

**Comment by andrew-d-taylor** [comment]
Closed as of commit: https://github.com/ScottKimball/SMWC/commit/0c8c8789394efce511a0ef724b8199488adc95b0
